#!/bin/bash

DIR=$5

# trap "grep packets; exit;" SIGHUP SIGINT SIGTERM 

# tcpdump tcp -i eth0 -s0 -nn -q -w receive.pcap
# Find ethernet name and use first ethernet interface. 

#targetMAC="00:1e:06:32:52:1e"
#targetMAC="80:e6:50:05:63:06"

# $1 method
# $2 pps 
# $3 packet size
# $4 sec 
pps=$2
packet_size=$3
sec=$4
so=$6
target_mac="$(ifconfig | grep Ethernet | awk '{print $5;}' | head -1)"

if [ "$target_mac" == "" ] ; then 
	echo "MAC address not available."
	exit
else
	echo "$target_mac available."
fi

ethname="$(ifconfig | grep $target_mac | awk '{print $1;}' | head -1)"

if [ "$ethname" == "" ] ; then
	echo "RECEIVER: Ethernet not available."
	exit
else 
	echo "RECEIVER: $ethname available."
fi

echo "RECEIVER: run tcpdump -i ${ethname} -s0 -nn -q -c $((pps*sec)) -w fname" 

#TODO(sungpia@me.com): find better way for detecting env and running appropriate command.
#sudo timeout $((sec+30)) tcpdump -i $ethname -s0 -nn -q -w $DIR/capture-${pps}-${packet_size}-${sec}-`date +"%Y-%m-%d-%H%M%S"`.pcap > $DIR/summary-${pps}-${packet_size}-${sec}-`date +"%Y-%m-%d-%H%M%S"` 2>&1  
sudo timeout $((sec+30)) tcpdump -i $ethname -s 1518 -nn -q -w $DIR/capture-${pps}-${packet_size}-${sec}-`date +"%Y-%m-%d-%H%M%S"`.pcap > $DIR/summary-${pps}-${packet_size}-${sec}-`date +"%Y-%m-%d-%H%M%S"` 2>&1

rm $DIR/cap*
sleep 5
  destip="192.168.0.15"
  summaryfname=$(ls ${DIR}/summary* | tr -d '\r')
  echo "RECEIVER: summary file found: $summaryfname"
  cap=$(cat $summaryfname | grep captured | awk '{print $1;}')
  sleep 1
  recv=$(cat $summaryfname | grep received | awk '{print $1;}')
  sleep 1
  drop=$(cat $summaryfname | grep "dropped by kernel" | awk '{print $1;}')
  sleep 1
  dropi=$(cat $summaryfname | grep "dropped by interface" | awk '{print $1;}')
  sleep 1

  #tcpdump -i $ethname -s 1518 -nn -q
  echo "RECEIVER: $cap, $recv, $drop, $dropi" 

  curl -s --data "dst_device=192.168.0.15&os=ubuntu-mate&pf_ring=false&ramdisk=false&io=${DIR}&mbps=$((pps*packet_size/1024/1024*8))&packet_size=${packet_size}&pps=${pps}&duration=${sec}&test_method=mgen&experiment_text_full=tcpdump -i $ethname -s 1518 -nn -q&send_option=$so&captured=${cap}&received_by_filter=${recv}&dropped_by_kernel=${drop}&dropped_by_interface=${dropi}" http://young.hanyang.ac.kr:5900/result > /dev/null

  rm $summaryfname

#grep packets ./summary | while read -r line ; do 
#  echo $line | awk '{print $1}' >> temp
#done
echo "RECEIVER: done tcpdump"
# Set network promiscuous
# euuuucho "ip link set $ethname promisc on"
#uu ip link set $ethname promisc on 

