#!/bin/bash

#TODO(sungpia@me.com): find way to grep mac 
target_mac="00:e0:4c:68:1c:66"
ethname="$(ifconfig | grep $target_mac | awk '{print $1;}' | head -1)"


if [ "$ethname" == "" ] ; then
	echo "Ethernet not available."
	exit
else 
	echo "$ethname available."
fi

cat ./sender.conf | while read line
do
  #TODO(sungpia@me.com): find more elegant way to handle input 
  method=$(echo $line | awk '{print $1}')
  pps=$(echo $line | awk '{print $2}')
  packet_size=$(echo $line | awk '{print $3}')
  ip_and_port=$(echo $line | awk '{print $4}')
  sec=$(echo $line | awk '{print $5}')

  echo "SENDER: USING ${method} to send to ${ip_and_port} for ${sec} seconds\b\tpps=${pps}, packet size=${packet_size}"
  echo "SENDER: init recieve side"

  ssh -t odroid@192.168.0.14 '~/Documents/dabada/receiver/dabada_receive' $method $pps $packet_size $sec
  if [ $method == "MGEN" ] ; then
    echo "0.0 ON 1 UDP SRC 5001 DST ${ip_and_port} COUNT $((sec * pps)) PERIODIC [${pps} ${packet_size}]" > tmp.mgn
  fi 
  mgen ipv4 interface $ethname input tmp.mgn hostAddr on 
  echo "SENDER: Done."
  sleep 5
done

rm ./tmp.mgn
